version: '3'
services:
  miniweibo-mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: miniweibo-mysql
    image: miniweibo-mysql
    ports:
      - 3306:3306

  miniweibo-redis:
    image: redis:7.0.0
    ports:
      - 6379:6379
    restart: always
    container_name: miniweibo-redis
    hostname: miniweibo-redis

  miniweibo-register:
    build:
      context: ./miniweibo-register
    restart: always
    ports:
      - 8848:8848
    container_name: miniweibo-register
    hostname: miniweibo-register
    image: miniweibo-register

  miniweibo-gateway:
    build:
      context: ./miniweibo-gateway
    restart: always
    ports:
      - 9999:9999
    container_name: miniweibo-gateway
    hostname: miniweibo-gateway
    image: miniweibo-gateway

  miniweibo-auth:
    build:
      context: ./miniweibo-auth
    restart: always
    container_name: miniweibo-auth
    hostname: miniweibo-auth
    image: miniweibo-auth

  miniweibo-upms:
    build:
      context: ./miniweibo-upms/miniweibo-upms-biz
    restart: always
    container_name: miniweibo-upms
    hostname: miniweibo-upms
    image: miniweibo-upms

  miniweibo-monitor:
    build:
      context: ./miniweibo-visual/miniweibo-monitor
    restart: always
    ports:
      - 5001:5001
    container_name: miniweibo-monitor
    hostname: miniweibo-monitor
    image: miniweibo-monitor

  miniweibo-sentinel:
    build:
      context: ./miniweibo-visual/miniweibo-sentinel-dashboard
    restart: always
    image: miniweibo-sentinel
    container_name: miniweibo-sentinel
    ports:
      - 5003:5003

  miniweibo-codegen:
    build:
      context: ./miniweibo-visual/miniweibo-codegen
    restart: always
    container_name: miniweibo-codegen
    hostname: miniweibo-codegen
    image: miniweibo-codegen

  miniweibo-job:
    build:
      context: ./miniweibo-visual/miniweibo-xxl-job-admin
    restart: always
    container_name: miniweibo-job
    hostname: miniweibo-job
    image: miniweibo-job
    ports:
      - 5004:5004
